# Principal Component Analysis (PCA)
- **Principal Component Analysis (PCA)** is a dimensionality reduction technique used to reduce the number of features in a dataset while retaining most of the variance present in the data. It achieves this by transforming the data into a new set of features called **principal components**, which are orthogonal and capture the maximum variance in the data.

## How PCA Works:
- **Standardize the Data**: Since PCA is affected by the scale of features, the data is usually standardized to have a mean of 0 and a variance of 1.
- **Compute the Covariance Matrix**: The covariance matrix describes the relationship between features in the data.
- **Compute the Eigenvalues and Eigenvectors**: Eigenvectors determine the direction of the principal components, and eigenvalues determine the magnitude (variance) captured by these components.
- **Sort and Select Principal Components**: The eigenvectors are sorted in descending order of their corresponding eigenvalues. The top k eigenvectors are selected to form the new feature space (where k is the number of desired components).
- **Transform the Data**: The original data is projected onto the selected principal components.


# Advantages of PCA
- **Reduces Dimensionality**: PCA helps reduce the number of features in the dataset, making it easier and faster to process, especially for large datasets.
- **Improves Performance**: By removing redundant or correlated features, PCA can improve the performance of machine learning models by reducing overfitting.
- **Captures Most Variance**: PCA retains the most important information by preserving the maximum variance, ensuring that the key patterns in the data are kept.
- **Enhances Visualization**: PCA helps visualize high-dimensional data by reducing it to 2 or 3 principal components, making it easier to interpret and understand.

| Aspect                   | Feature Selection                            | Principal Component Analysis (PCA)          |
|--------------------------|----------------------------------------------|---------------------------------------------|
| **Definition**            | Choosing a subset of original features.      | Creating new features by combining original ones. |
| **Purpose**               | To retain the most important features.       | To reduce the number of dimensions while retaining the variance. |
| **Process**               | Eliminates irrelevant or redundant features. | Transforms original features into new uncorrelated components. |
| **Output**                | A smaller subset of the original features.   | New components that are linear combinations of the original features. |
| **Interpretability**      | Retained features are easy to interpret.     | New components may not have an intuitive interpretation. |
| **Preserving Variance**   | Does not guarantee variance preservation.     | Maximizes variance along the new components. |
| **Example**               | Selecting the top 5 features based on correlation or importance. | Reducing from 10 features to 3 components that capture most variance. |
| **Use Case**              | When you want to keep original features.     | When you want to reduce dimensions and capture the most variance. |
| **Impact on Model**       | Direct impact by removing irrelevant features. | Indirect impact by changing the feature space. |


## Python Implementation of PCA 

In [6]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA

# Step 1: Create the DataFrame
data = {
    'Target': [0, 1, 0, 1],
    'Feature 1': [2, 1, 3, 2],
    'Feature 2': [4, 3, 5, 6],
    'Feature 3': [6, 5, 7, 8],
    'Feature 4': [8, 7, 9, 10]
}
df = pd.DataFrame(data)

# Step 2: Extract features and mean-center them
X = df[['Feature 1', 'Feature 2', 'Feature 3', 'Feature 4']].values
X_mean = X - np.mean(X, axis=0)

# Step 3: Calculate the covariance matrix
cov_matrix = np.cov(X_mean, rowvar=False)
print("Covariance Matrix:\n", cov_matrix)

# Step 4: Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

# Step 5: Perform PCA using sklearn
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)
print("PCA Transformed Data:\n", X_pca)

Covariance Matrix:
 [[0.66666667 0.66666667 0.66666667 0.66666667]
 [0.66666667 1.66666667 1.66666667 1.66666667]
 [0.66666667 1.66666667 1.66666667 1.66666667]
 [0.66666667 1.66666667 1.66666667 1.66666667]]
Eigenvalues:
 [3.78180023e-01 5.28848664e+00 1.68501120e-32 1.36845553e-48]
Eigenvectors:
 [[-9.70179752e-01 -2.42386568e-01  7.85046229e-17 -1.22607339e-32]
 [ 1.39941950e-01 -5.60133541e-01  8.16496581e-01  1.54125491e-17]
 [ 1.39941950e-01 -5.60133541e-01 -4.08248290e-01 -7.07106781e-01]
 [ 1.39941950e-01 -5.60133541e-01 -4.08248290e-01  7.07106781e-01]]
PCA Transformed Data:
 [[-0.84020031  0.20991293]
 [-2.7629875  -0.34044098]
 [ 1.08258688  0.76026683]
 [ 2.52060094 -0.62973878]]


In [7]:
# Convert PCA transformed data into a DataFrame
pca_df = pd.DataFrame(X_pca, columns=['Principal Component 1', 'Principal Component 2'])

# Include the target variable for reference
pca_df['Target'] = df['Target']

print("PCA Transformed DataFrame:\n", pca_df)

PCA Transformed DataFrame:
    Principal Component 1  Principal Component 2  Target
0              -0.840200               0.209913       0
1              -2.762988              -0.340441       1
2               1.082587               0.760267       0
3               2.520601              -0.629739       1
